export const nutrients = {
	"Soybean": {
		"calories_kcal": 446,
		"protein_g": 36.5,
		"carbs_g": 30.2,
		"fat_g": 19.9,
		"fiber_g": 9.3,
		"vitaminA_ug": 20,
		"vitaminC_mg": 6,
		"iron_mg": 15.7,
		"calcium_mg": 277,
		"source": "USDA FoodData Central"
	},
	"Lettuce (Green leaf)": {
		"calories_kcal": 15,
		"protein_g": 1.4,
		"carbs_g": 2.9,
		"fat_g": 0.2,
		"fiber_g": 1.3,
		"vitaminA_ug": 740,
		"vitaminC_mg": 9.2,
		"iron_mg": 0.9,
		"calcium_mg": 36,
		"source": "USDA FoodData Central"
	},
	"Carrot": {
		"calories_kcal": 41,
		"protein_g": 0.9,
		"carbs_g": 10.0,
		"fat_g": 0.2,
		"fiber_g": 2.8,
		"vitaminA_ug": 835,
		"vitaminC_mg": 5.9,
		"iron_mg": 0.3,
		"calcium_mg": 33,
		"source": "USDA FoodData Central"
	},
	"Sweet potato": {
		"calories_kcal": 86,
		"protein_g": 1.6,
		"carbs_g": 20.1,
		"fat_g": 0.1,
		"fiber_g": 3.0,
		"vitaminA_ug": 709,
		"vitaminC_mg": 2.4,
		"iron_mg": 0.6,
		"calcium_mg": 30,
		"source": "USDA FoodData Central"
	},
	"Chickpea": {
		"calories_kcal": 164,
		"protein_g": 8.9,
		"carbs_g": 27.4,
		"fat_g": 2.6,
		"fiber_g": 7.6,
		"vitaminA_ug": 67,
		"vitaminC_mg": 1.3,
		"iron_mg": 2.9,
		"calcium_mg": 49,
		"source": "USDA FoodData Central"
	},
	"Tomato": {
		"calories_kcal": 18,
		"protein_g": 0.9,
		"carbs_g": 3.9,
		"fat_g": 0.2,
		"fiber_g": 1.2,
		"vitaminA_ug": 42,
		"vitaminC_mg": 13.7,
		"iron_mg": 0.3,
		"calcium_mg": 10,
		"source": "USDA FoodData Central"
	},
	"Wheat": {
		"calories_kcal": 339,
		"protein_g": 13.7,
		"carbs_g": 71.2,
		"fat_g": 2.5,
		"fiber_g": 12.2,
		"vitaminA_ug": 0,
		"vitaminC_mg": 0,
		"iron_mg": 3.9,
		"calcium_mg": 29,
		"source": "USDA FoodData Central"
	},
	"Dill": {
		"calories_kcal": 43,
		"protein_g": 3.5,
		"carbs_g": 7.0,
		"fat_g": 1.1,
		"fiber_g": 2.1,
		"vitaminA_ug": 200,
		"vitaminC_mg": 85,
		"iron_mg": 6.6,
		"calcium_mg": 208,
		"source": "USDA FoodData Central"
	},
	"Basil": {
		"calories_kcal": 23,
		"protein_g": 3.2,
		"carbs_g": 2.7,
		"fat_g": 0.6,
		"fiber_g": 1.6,
		"vitaminA_ug": 264,
		"vitaminC_mg": 18.0,
		"iron_mg": 3.2,
		"calcium_mg": 177,
		"source": "USDA FoodData Central"
	},
	"Coffee beans": {
		"calories_kcal": 2,
		"protein_g": 0.1,
		"carbs_g": 0.0,
		"fat_g": 0.0,
		"fiber_g": 0.0,
		"vitaminA_ug": 0,
		"vitaminC_mg": 0,
		"iron_mg": 0.1,
		"calcium_mg": 7,
		"source": "Open Food Facts / generic"
	},
	"Tea leaves": {
		"calories_kcal": 1,
		"protein_g": 0.1,
		"carbs_g": 0.2,
		"fat_g": 0.0,
		"fiber_g": 0.0,
		"vitaminA_ug": 0,
		"vitaminC_mg": 0,
		"iron_mg": 0.1,
		"calcium_mg": 0,
		"source": "Open Food Facts / generic"
	}
}